version: "2.2"
services:
  go-rest:
    container_name: go-rest-api
    build: .
    expose:
      - "8080"
    env_file:
      - ./config/dev.env
    depends_on:
      - mongo
    ports:
      - "8080:8080"
  mongo:
    image: mongo
    container_name: "go-rest-db"
    ports:
      - "27017:27017"